# Build:  cargo +nightly build -Z json-target-spec --release

[build]
target = "mips-rv6699.json"

[unstable]
build-std = ["core", "alloc", "panic_abort"]
build-std-features = ["compiler-builtins-mem"]

[target.mips-rv6699]
linker = "mips-linux-muslsf-gcc"
rustflags = [
  "-C", "target-cpu=mips32",
  "-C", "relocation-model=static",
  "-C", "link-arg=-static",
  "-C", "link-arg=-no-pie",
  "-C", "link-arg=-Wl,-Bstatic",
  "-C", "link-arg=-l:libc.a",
]
