# Build:  cargo +nightly build -Z json-target-spec --release

[build]
target = "mips-rv6699.json"

[unstable]
build-std = ["core", "alloc", "panic_abort"]
# provides memcpy/memset/memcmp/bcmp/memmove from compiler_builtins (we link -lc too as backup)
build-std-features = ["compiler-builtins-mem"]

[target.mips-rv6699]
linker = "mips-linux-muslsf-gcc"
rustflags = [
  "-C", "target-cpu=mips32",
  "-C", "relocation-model=static",
  "-C", "link-arg=-static",
  "-C", "link-arg=-no-pie",
  "-C", "link-arg=-lc",
]
